project_name: ts
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
      - android
    goarch:
      - amd64
      - arm64
    binary: ts
archives:
  - name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - ts.zsh
